name: fpde-repro
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - numpy
  - pandas
  - tabulate
  - jinja2
  - pyyaml
  - scikit-learn
  - scipy
  - matplotlib
  - umap-learn
  - seaborn
  - pip:
      - fpde @ git+https://github.com/fpde-xai/fpde.git@dynamic
      - lightgbm
      - openml
      - shap
      - lime
      - aime-xai
      - pytest
      - pyarrow
      - librosa
      - soundfile
